// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENHFszlNIq8J5h0vVY4VSAX_40rDTOkA',
    appId: '1:184079378437:web:0e922372609e949469946c',
    messagingSenderId: '184079378437',
    projectId: 'demos-6737f',
    authDomain: 'demos-6737f.firebaseapp.com',
    storageBucket: 'demos-6737f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsAq0tpQG7B9mnKHGkKBAq8CWb1zkoCk4',
    appId: '1:184079378437:android:9f0b71befeede70a69946c',
    messagingSenderId: '184079378437',
    projectId: 'demos-6737f',
    storageBucket: 'demos-6737f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaWlnIOPAiXycuhjWamBO7u3WrhgMIOaY',
    appId: '1:184079378437:ios:d44d2b7e9e1d0d4769946c',
    messagingSenderId: '184079378437',
    projectId: 'demos-6737f',
    storageBucket: 'demos-6737f.appspot.com',
    iosClientId: '184079378437-mggikes0r5rue0adnrmnptpuemv87mfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.demos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaWlnIOPAiXycuhjWamBO7u3WrhgMIOaY',
    appId: '1:184079378437:ios:d44d2b7e9e1d0d4769946c',
    messagingSenderId: '184079378437',
    projectId: 'demos-6737f',
    storageBucket: 'demos-6737f.appspot.com',
    iosClientId: '184079378437-mggikes0r5rue0adnrmnptpuemv87mfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.demos',
  );
}
